pi@raspberrypi:~/Downloads/ilyass-main/PythonProject $ source venv/bin/activate
(venv) pi@raspberrypi:~/Downloads/ilyass-main/PythonProject $ python Window.py
Connexion MariaDB réussie !
Exception in thread Thread-1 (_start_listen):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Downloads/ilyass-main/PythonProject/venv/lib/python3.11/site-packages/firebase_admin/db.py", line 128, in _start_listen
    self._callback(Event(sse_event))
  File "/home/pi/Downloads/ilyass-main/PythonProject/Window.py", line 98, in sync_test_mode
    new_mode = event.data.val()
               ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'val'
Trappe ouverte.
Alarme activée!
